// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 7.2
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_blinds(m,l,a){var h=jQuery;var k=h(this);var d=m.parts||3;var j=h("<div>").addClass("ws_effect ws_blinds").css({position:"absolute",width:"100%",height:"100%",left:0,top:0,"z-index":8}).hide().appendTo(a);var e=h("<div>").css({position:"absolute",top:0,left:0,width:"100%",height:"100%",overflow:"hidden"}).appendTo(j);var f=[];var c=document.addEventListener;for(var g=0;g<d;g++){f[g]=h("<div>").css({position:c?"relative":"absolute",display:c?"inline-block":"block",height:"100%",width:(100/d+0.001).toFixed(3)+"%",border:"none",margin:0,overflow:"hidden",top:0,left:c?0:((100*g/d).toFixed(3)+"%")}).appendTo(j)}function b(q,n,o,i,p){if(m.support.transform&&m.support.transition){if(!n.transform){n.transform=""}if(n.left){n.transform+=" translate3d("+(n.left?n.left:0)+"px,0,0)"}delete n.left;if(o||i){n.transition=o+"ms all "+i+"ms ease-in-out"}q.css(n);if(p){q.on("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd",p)}}else{if(o){q.animate(n,o,"swing",p)}else{q.css(n)}}}this.go=function(r,p,o){if(o==undefined){o=p>r?1:0}j.find("img").stop(true,true);j.show();var u=h(".ws_list",a);if(m.fadeOut){u.fadeOut((1-1/d)*m.duration)}var s=h(l[p]);var t={width:s.width()||m.width,height:s.height()||m.height};var v=s.clone().css(t).appendTo(e);b(v,{left:0});b(v,{left:(!o?1:-1)*v.width()*0.5},m.duration,m.duration*0.1);for(var q=0;q<f.length;q++){var n=f[q];var w=h(l[r]).clone().css({position:"absolute",top:0}).css(t).appendTo(n);b(w,{left:(!o?(-w.width()):(w.width()-n.position().left))});b(w,{left:-n.position().left},(m.duration/(f.length+1))*(o?(f.length-q+1):(q+2)),0,((!o&&q==f.length-1||o&&!q)?function(){k.trigger("effectEnd");j.hide().find("img").remove();v.remove()}:false))}}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 7.2
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"blinds",prev:"",next:"",duration:20*100,delay:41*100,width:830,height:360,autoPlay:true,autoPlayVideo:false,playPause:false,stopOnHover:false,loop:false,bullets:1,caption:true,captionEffect:"parallax",controls:true,responsive:1,fullScreen:false,gestures:2,onBeforeStep:0,images:0});